export const RESTORE_DATA = "RESTORE_DATA";
export const RESTORE_DATA_FINISHED = "RESTORE_DATA_FINISHED";

export const MODIFY_MEMBERS = "MODIFY_MEMBERS";

export const GENERATE_DATA = "GENERATE_DATA";
export const GENERATE_DATA_FINISHED = "GENERATE_DATA_FINISHED";
